### ISSUE TITLE
Script doesn't work on windows 8.1

### ISSUE THREAD

**Issue by whitecollar17** [roderickvd/ppscripts#3]
Everytime it give me the following error when running:

Post-process-script RenameMedia.py for XXXXXXXX failed (terminated with unknown status)

:(

**Comment by roderickvd** [comment]
Windows is not supported.

**Comment by whitecollar17** [comment]
Why not?

**Comment by roderickvd** [comment]
Because Windows does not have the required command line utilities. Feel free to contribute a Windows-compatible solution and I will consider it for merging.
